branches:
  only:
    - master

notifications:
  email: false
  slack: jotc:Ok7TY1zpz3fxsdpZqnqZovfi

addons:
  code_climate:
    repo_token: 3ac41b4e23ebcc5ef00f749e8d111792045f651929bb23bba75396a6717522e3

language: node_js
node_js:
  - "4.2"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# Dependencies
services:
  - mongodb

before_script:
  - npm run coverage >/dev/null &
  - sleep 30

after_script:
  - killall -SIGINT node
  - sleep 5
  - codeclimate-test-reporter < coverage/lcov.info
