branches:
  only:
    - master

notifications:
  slack: jotc:Ok7TY1zpz3fxsdpZqnqZovfi

language: node_js
node_js:
  - "0.12"

# Dependencies
services:
  - mongodb

sudo:
  - required

before_script:
  - cd server
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
  - npm install
  - node server &>/dev/null &
  - sleep 5
