notifications:
  email: false
  slack: jotc:Ok7TY1zpz3fxsdpZqnqZovfi
language: node_js
node_js:
- '6.3'
- '6.9'
- '7.0'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- mongodb
before_script:
- npm run coverage >/dev/null &
- sleep 30
after_script:
- killall -SIGINT node
- sleep 5
- CODECLIMATE_REPO_TOKEN=3ac41b4e23ebcc5ef00f749e8d111792045f651929bb23bba75396a6717522e3
  ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
before_deploy:
- openssl aes-256-cbc -K $encrypted_20f25f543587_key -iv $encrypted_20f25f543587_iv
  -in deploy/deploy.key.enc -out deploy/deploy.key -d
deploy:
  provider: script
  script: deploy/run.sh
  on:
    branch: development
before_install:
- openssl aes-256-cbc -K $encrypted_20f25f543587_key -iv $encrypted_20f25f543587_iv
  -in deploy.key.enc -out deploy/deploy.key -d
